[cockroach]
host = "localhost"
port = "26257"
user = "root"
dbName = "imdb"
password = ""
dialect = "postgres"

[omdb]
apikey = "" # Your omdb api key if you dont have than generate by visting : [http://www.omdbapi.com/apikey.aspx]